version: 2
updates:
  - package-ecosystem: "pip" # Python's dependency management system
    directory: "/"          # Root directory where requirements.txt is located
    schedule:
      interval: "weekly"    # Check for updates every week
