apiVersion: v1
kind: Service
metadata:
  name: argo-nodeport
  namespace: argocd
spec:
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort
